import {SHAPES,COLOURS,isMatch,clampScore,completionMessage} from "./logic.js";
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
let score=0,total=0; const scoreEl=$("#score"),messageEl=$("#message");
function updateScore(){score=clampScore(score,total);scoreEl.textContent=`${score} / ${total}`;messageEl.textContent=completionMessage(score,total)}
function mark(el,ok,yes,no){el.classList.remove("success","retry");el.classList.add(ok?"success":"retry");el.textContent=ok?yes:no}
function initShape(){const a=$("#shape-match"),p=$(".prompt",a),r=$(".result",a),expected=SHAPES[Math.floor(Math.random()*SHAPES.length)];p.textContent=`Find the ${expected}`;total++;$$('.choice',a).forEach(b=>b.addEventListener('click',()=>{const ok=isMatch(expected,b.dataset.value);if(ok&&a.dataset.done!=="1"){score++;a.dataset.done="1"}mark(r,ok,"Yes! That shape belongs here. 🌟","Almost — try another shape.");updateScore()}))}
function initColour(){const a=$("#colour-match"),t=$(".colour-target",a),r=$(".result",a),expected=COLOURS[Math.floor(Math.random()*COLOURS.length)];t.dataset.colour=expected;t.setAttribute('aria-label',`Target colour: ${expected}`);total++;$$('.swatch',a).forEach(b=>b.addEventListener('click',()=>{const ok=isMatch(expected,b.dataset.value);if(ok&&a.dataset.done!=="1"){score++;a.dataset.done="1"}mark(r,ok,"Lovely colour match! 🎨","Good try — choose another colour.");updateScore()}))}
function initSorting(){const a=$("#sorting"),cards=$$('.sort-card',a),zones=$$('.sort-zone',a),r=$(".result",a),solved=new Set();total+=cards.length;function place(card,zone){const ok=card.dataset.group===zone.dataset.group;if(ok&&!solved.has(card.id)){solved.add(card.id);score++;card.classList.add('sorted');zone.appendChild(card)}mark(r,ok,"Great sorting! 🌻","That one grows in a different bed.");updateScore()}cards.forEach(card=>{card.draggable=true;card.addEventListener('dragstart',e=>e.dataTransfer.setData('text/plain',card.id));card.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();card.classList.toggle('selected');r.textContent=card.classList.contains('selected')?'Now choose a garden bed.':''}})});zones.forEach(z=>{z.addEventListener('dragover',e=>e.preventDefault());z.addEventListener('drop',e=>{e.preventDefault();const c=document.getElementById(e.dataTransfer.getData('text/plain'));if(c)place(c,z)});z.addEventListener('click',()=>{const c=$('.sort-card.selected');if(c){c.classList.remove('selected');place(c,z)}})})}
$("#reset").addEventListener('click',()=>location.reload());initShape();initColour();initSorting();updateScore();
